---
openapi: 3.0.0
info:
  title: Bilsoft E-Fatura API
  description: Bilsoft E-Fatura API dökümantasyonu
  version: v1.2
servers:
- url: https://virtserver.swaggerhub.com/Muammeryeni/swagtoredoc/v1.2
  description: SwaggerHub API Auto Mocking
paths:
  /AktivasyonEkle:
    post:
      summary: Aktivasyon ekle
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AktivasyonEkleRequest'
        required: true
      responses:
        "200":
          description: Başarılı
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AktivasyonEkleResponse'
        "400":
          description: Hatalı istek
components:
  schemas:
    Authentication:
      type: object
      properties:
        Kullanici:
          type: string
        Sifre:
          type: string
        ApiTur:
          type: string
        Spy:
          $ref: '#/components/schemas/Authentication_Spy'
    KullaniciBilgileri:
      type: object
      properties:
        xsltEfatura:
          type: string
        xsltEarsiv:
          type: string
        servisUrl:
          type: string
        kullanici:
          type: string
        sifre:
          type: string
        GelenStokKaydet:
          type: boolean
        vtBilgiler:
          $ref: '#/components/schemas/KullaniciBilgileri_vtBilgiler'
        EFaturaSeriBaslik:
          type: string
        EArsivSeriBaslik:
          type: string
        SeciliGBEtiketi:
          type: string
        entegrasyonTur:
          type: string
          enum:
          - EFatura
          - EIrsaliye
          - BilsoftMail
          - EMustahsil
        logoSessionID:
          type: string
        logo2FACode:
          type: string
        gibMi:
          type: boolean
        FirmaVergiNo:
          type: string
    AutHeader:
      type: object
      properties:
        Donem:
          type: string
        VergiNo:
          type: string
        VeritabaniAd:
          type: string
        KullaniciAdi:
          type: string
        Sifre:
          type: string
        Sube:
          type: string
        IpAdresi:
          type: string
        MacAdresi:
          type: string
        DovizAktifMi:
          type: string
    Aktivasyon:
      type: object
      properties:
        AktivasyonTip:
          type: string
        AktivasyonTarih:
          type: string
          format: date-time
        Pk:
          type: string
        Gb:
          type: string
        SeriBaslik:
          type: string
    MusteriEkle:
      type: object
      properties:
        Unvan:
          type: string
        Yetkili:
          type: string
        YetkiliTckn:
          type: string
        VknTckn:
          type: string
        VergiDairesi:
          type: string
        TicaretSicilNo:
          type: string
        Tel:
          type: string
        Email:
          type: string
        Fax:
          type: string
        Website:
          type: string
        Ulke:
          type: string
        Il:
          type: string
        Ilce:
          type: string
        Adres:
          type: string
        Aktivasyonlar:
          type: array
          items:
            $ref: '#/components/schemas/Aktivasyon'
    AktivasyonEkleRequest:
      type: object
      properties:
        Envelope:
          $ref: '#/components/schemas/AktivasyonEkleRequest_Envelope'
    AktivasyonEkleResponse:
      type: object
      properties:
        Envelope:
          $ref: '#/components/schemas/AktivasyonEkleResponse_Envelope'
    Authentication_Spy:
      type: object
      properties:
        Spy1:
          type: string
        Spy2:
          type: string
    KullaniciBilgileri_vtBilgiler:
      type: object
      properties:
        Server:
          type: string
        Port:
          type: string
        Database:
          type: string
        VKullanici:
          type: string
        VSifre:
          type: string
        WebServisMesaj:
          type: string
        WebServisCevap:
          type: string
    AktivasyonEkleRequest_Envelope_Header:
      type: object
      properties:
        Authentication:
          $ref: '#/components/schemas/Authentication'
        KullaniciBilgileri:
          $ref: '#/components/schemas/KullaniciBilgileri'
        AutHeader:
          $ref: '#/components/schemas/AutHeader'
    AktivasyonEkleRequest_Envelope_Body_AktivasyonEkle:
      type: object
      properties:
        musteriEkle:
          $ref: '#/components/schemas/MusteriEkle'
    AktivasyonEkleRequest_Envelope_Body:
      type: object
      properties:
        AktivasyonEkle:
          $ref: '#/components/schemas/AktivasyonEkleRequest_Envelope_Body_AktivasyonEkle'
    AktivasyonEkleRequest_Envelope:
      type: object
      properties:
        Header:
          $ref: '#/components/schemas/AktivasyonEkleRequest_Envelope_Header'
        Body:
          $ref: '#/components/schemas/AktivasyonEkleRequest_Envelope_Body'
    AktivasyonEkleResponse_Envelope_Body_AktivasyonEkleResponse_AktivasyonEkleResult:
      type: object
      properties:
        basariliMi:
          type: boolean
        mesaj:
          type: string
        veri:
          type: string
        efaturaNo:
          type: string
        efaturaId:
          type: string
        efaturaSenaryo:
          type: string
        fisNo:
          type: integer
        evrakNo:
          type: string
        efaturaDurum:
          type: string
    AktivasyonEkleResponse_Envelope_Body_AktivasyonEkleResponse:
      type: object
      properties:
        AktivasyonEkleResult:
          $ref: '#/components/schemas/AktivasyonEkleResponse_Envelope_Body_AktivasyonEkleResponse_AktivasyonEkleResult'
    AktivasyonEkleResponse_Envelope_Body:
      type: object
      properties:
        AktivasyonEkleResponse:
          $ref: '#/components/schemas/AktivasyonEkleResponse_Envelope_Body_AktivasyonEkleResponse'
    AktivasyonEkleResponse_Envelope:
      type: object
      properties:
        Body:
          $ref: '#/components/schemas/AktivasyonEkleResponse_Envelope_Body'
